version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: AppCont
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres_db
    environment:
      - SERVER_PORT=8080
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=admin_franchise
      - POSTGRES_SSLMODE=disable
      - POSTGRES_MAX_IDLE_CONNS=10
      - POSTGRES_MAX_OPEN_CONNS=10

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=admin_franchise
    ports:
      - '5433:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
