name: Run Linter and Tests
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Running CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54